---
- name: WINDOWS-LAN-UPDATE
  hosts: all
  gather_facts: false
  
  tasks:
    - name: installing updates
      win_updates:
        category_names: ["CriticalUpdates", "SecurityUpdates", "UpdateRollups"]
        whitelist:
         - KB4577586
         - KB5001648
        reboot: yes
        reboot_timeout: 1200
